### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

### ISSUE THREAD

**Issue by JokyVM** [bigpon/QPNet#2]
Hello

First of all, thank you for sharing this project.
I would like to evaluate the performance of the vocoder by running one of your pre-trained model. However, after extracting the features of a test file with runFE script, it get an error when trying to read the generated files in qpnet_decode.py

The call to qpnet_decode is as follows :
```
python ./bin/qpnet_decode.py 
--feats /home/Julien/QPNet-master/QPNet-master/h5/33.h5 
--stats /home/Julien/QPNet-master/QPNet-master/corpus/VCC2018/stats/list_stats.h5 
--config /home/Julien/QPNet-master/QPNet-master/qpnet_models/Avcc18tr_Wvcc18tr_d8/model.conf 
--outdir /home/Julien/QPNet-master/QPNet-master/qpnet_output/feat_id.wav 
--checkpoint /home/Julien/QPNet-master/QPNet-master/qpnet_models/Avcc18tr_Wvcc18tr_d8//checkpoint-final.pkl 
--fs 22050 --batch_size 1 --extra_memory False --seed 100 --n_gpus 2 --f0_factor 1.0 --f0_dim_index 1
```

As input, I use a 22050Hz wav file (33.wav) and I generated the feats and stats using step 2 and 3 of runFE.py

The complete error message is :
```
Traceback (most recent call last):
  File "./bin/qpnet_decode.py", line 335, in <module>
    main()
  File "./bin/qpnet_decode.py", line 252, in main
    feat_list = read_txt(args.feats)
  File "/home/Julien/QPNet-master/QPNet-master/src/utils/utils.py", line 161, in read_txt
    filenames = f.readlines()
  File "/home/Julien/miniconda3/envs/venvQPNet/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

Could you please help me with this ? I guess I might be doing this the wrong way but I don't know how else I can simply extract the features of a test file and try out a model with it 

Thanks again for sharing this and for your time

**Comment by bigpon** [comment]
Hi @JokyVM ,
sorry for the late reply.
According to your message, the problem occurs when the program reads your file list.
Therefore, please check your file list.
You may put one simple file path in your file list first for debugging.
